apiVersion: "bookkeeper.pravega.io/v1alpha1"
kind: "BookkeeperCluster"
metadata:
  name: "pravega-bk"
replicas: 5
image:
  repository: pravega/bookkeeper
  pullPolicy: IfNotPresent
version: 0.7.0
pravegaClusterName: pravega
zookeeperUri: zookeeper-client:2181
autoRecovery: true
storage:
  className: standard
jvmOptions:
  memoryOpts:
    - "-Xms2g"
    - "-Xmx4g"
    - "-XX:MaxDirectMemorySize=4g"
resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 4000m
    memory: 8Gi
options:
  enableStatistics: "true"
  statsProviderClass: "org.apache.bookkeeper.stats.prometheus.PrometheusMetricsProvider"