## Default values for bookkeeper.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.
apiVersion: "bookkeeper.pravega.io/v1alpha1"
kind: "BookkeeperCluster"
metadata:
  name: "pravega-bk"
version: 0.7.1-2526.b90d6ba96

image:
  repository: devops-repo.isus.emc.com:8116/nautilus/bookkeeper
  tag: 0.7.1-2526.b90d6ba96
  pullPolicy: IfNotPresent

hooks:
  image:
    repository: lachlanevenson/k8s-kubectl
    tag: v1.16.10
replicas: 4
zookeeperUri: 10.107.39.26:2181
pravegaClusterName: prvg-pravega
autoRecovery: true
resources:
  requests:
    cpu: 2000m
    memory: 2Gi
  limits:
    cpu: 2
    memory: 2Gi
jvmOptions:
  memoryOpts: ["-Xms500M", "-Xmx500M", "-XX:MaxDirectMemorySize=500M","-XX:+HeapDumpOnOutOfMemoryError", "-XX:HeapDumpPath=/opt/","-XX:NativeMemoryTracking=detail"]
  gcOpts: []
  gcLoggingOpts: []
  extraOpts: []
debugLogging: true
options:
  enableStatistics: "true"
  statsProviderClass: "org.apache.bookkeeper.stats.prometheus.PrometheusMetricsProvider"
  log.level: "DEBUG"
  ledgerStorageClass: "org.apache.bookkeeper.bookie.InterleavedLedgerStorage"
  flushEntrylogBytes: "134217728"
  minorCompactionThreshold: "0.4"       
  minorCompactionInterval: "1800"       
  majorCompactionThreshold: "0.8"       
  majorCompactionInterval: "43200"       
  isForceGCAllowWhenNoSpace: "true"
  gcWaitTime: "600000"
  flushEntrylogBytes: "134217728"
