## Default values for bookkeeper.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.
apiVersion: "bookkeeper.pravega.io/v1alpha1"
kind: "BookkeeperCluster"
metadata:
  name: "pravega-bk"
version: 0.7.0

image:
  repository: pravega/bookkeeper
  pullPolicy: IfNotPresent

hooks:
  image:
    repository: lachlanevenson/k8s-kubectl
    tag: v1.16.10
replicas: 4
zookeeperUri: zk-client:2181
pravegaClusterName: pravega
autoRecovery: true
resources:
  requests:
    cpu: 2000m
    memory: 8Gi
  limits:
    cpu: 4
    memory: 16Gi
jvmOptions:
  memoryOpts: ["-Xmx2g", "-XX:MaxDirectMemorySize=14g"]
  gcOpts: []
  gcLoggingOpts: []
  extraOpts: []
debugLogging: true
options:
  enableStatistics: "true"
  statsProviderClass: "org.apache.bookkeeper.stats.prometheus.PrometheusMetricsProvider"
  log.level: "DEBUG"
