## Default values for bookkeeper.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.
apiVersion: "bookkeeper.pravega.io/v1alpha1"
kind: "BookkeeperCluster"
metadata:
  name: "pravega-bk"
version: 0.7.0

image:
  repository: pravega/bookkeeper
  pullPolicy: IfNotPresent

hooks:
  image:
    repository: lachlanevenson/k8s-kubectl
    tag: v1.16.10

replicas: 3
zookeeperUri: zk-client:2181
pravegaClusterName: pravega
autoRecovery: true
resources:
  requests:
    cpu: 1000m
    memory: 3Gi
  limits:
    cpu: 2
    memory: 3Gi

jvmOptions:
  memoryOpts: ["-Xmx1g", "-XX:MaxDirectMemorySize=2g"]
  gcOpts: []
  gcLoggingOpts: []
  extraOpts: []

options:
  enableStatistics: "true"
  statsProviderClass: "org.apache.bookkeeper.stats.prometheus.PrometheusMetricsProvider"
  minorCompactionThreshold: "0.4"       
  minorCompactionInterval: "1800"       
  majorCompactionThreshold: "0.8"       
  majorCompactionInterval: "43200" 
  isForceGCAllowWhenNoSpace: "true" 
