apiVersion: "bookkeeper.pravega.io/v1alpha1"
kind: "BookkeeperCluster"
metadata:
  name: "pravega-bk"
replicas: 3
image:
  repository: pravega/bookkeeper
  pullPolicy: IfNotPresent
version: 0.7.0
pravegaClusterName: pravega
zookeeperUri: zookeeper-client:2181
autoRecovery: true
storage:
  className: standard
jvmOptions:
  memoryOpts:
    - "-Xms1g"
    - "-Xmx2g"
    - "-XX:MaxDirectMemorySize=2g"
resources:
  limits:
    cpu: 3000m
    memory: 4Gi
  requests:
    cpu: 1000m
    memory: 4Gi
options:
  enableStatistics: "true"
  statsProviderClass: "org.apache.bookkeeper.stats.prometheus.PrometheusMetricsProvider"