apiVersion: "bookkeeper.pravega.io/v1alpha1"
kind: "BookkeeperCluster"
metadata:
  name: "pravega-bk"
replicas: 3
image:
  repository: pravega/bookkeeper
  pullPolicy: IfNotPresent
version: 0.7.0
pravegaClusterName: pravega
zookeeperUri: zookeeper-client:2181
autoRecovery: true
storage:
  className: standard
jvmOptions:
  memoryOpts:
    - "-Xms2g"
    - "-Xmx10g"
    - "-XX:MaxDirectMemorySize=10g"
resources:
  limits:
    cpu: 8000m
    memory: 10Gi
  requests:
    cpu: 2000m
    memory: 6Gi
options:
  enableStatistics: "true"
  statsProviderClass: "org.apache.bookkeeper.stats.prometheus.PrometheusMetricsProvider"
