apiVersion: "bookkeeper.pravega.io/v1alpha1"
kind: "BookkeeperCluster"
metadata:
  name: "pravega-bk"
replicas: 3
image:
  repository: pravega/bookkeeper
  pullPolicy: IfNotPresent
version: 0.7.0
pravegaClusterName: pravega
zookeeperUri: zookeeper-client:2181
autoRecovery: true
storage:
  className: standard
jvmOptions:
  memoryOpts:
    - "-Xms2g"
    - "-Xmx24g"
    - "-XX:MaxDirectMemorySize=8g"
resources:
  limits:
    cpu: 8000m
    memory: 12Gi
  requests:
    cpu: 2000m
    memory: 8Gi
