## Default values for bookkeeper.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.
apiVersion: "bookkeeper.pravega.io/v1alpha1"
kind: "BookkeeperCluster"
metadata:
  name: "pravega-bk"
version: 0.9.0-2641.0c98b91cd
image:
  repository: devops-repo.isus.emc.com:8116/nautilus/bookkeeper
  tag: 0.9.0-2641.0c98b91cd
  pullPolicy: IfNotPresent
hooks:
  image:
    repository: lachlanevenson/k8s-kubectl
    tag: v1.16.10
replicas: 4
zookeeperUri: 10.107.39.26:2181
pravegaClusterName: prvg-pravega
autoRecovery: true
resources:
  requests:
    cpu: 2000m
    memory: 5Gi
  limits:
    cpu: 2
    memory: 5Gi
jvmOptions:
  memoryOpts: [ "-Xmx1843m", "-XX:MaxDirectMemorySize=1843m" ,"-XX:+HeapDumpOnOutOfMemoryError", "-XX:HeapDumpPath=/bk/ledgers","-XX:NativeMemoryTracking=detail"]
  gcOpts: []
  gcLoggingOpts: []
  extraOpts: []
debugLogging: true
options:
  enableStatistics: "true"
  statsProviderClass: "org.apache.bookkeeper.stats.prometheus.PrometheusMetricsProvider"
  log.level: "INFO"
  ledgerStorageClass: "org.apache.bookkeeper.bookie.InterleavedLedgerStorage"
  flushEntrylogBytes: "134217728"
  minorCompactionThreshold: "0.4"
  minorCompactionInterval: "3600"
  majorCompactionThreshold: "0.8"
  majorCompactionInterval: "43200"
  isForceGCAllowWhenNoSpace: "true"
  gcWaitTime: "600000"
  flushEntrylogBytes: "134217728"
  isThrottleByBytes: "true"
  compactionRateByBytes: "1000000"
  # Throttle compaction by bytes or by entries.
  # isThrottleByBytes=false
  # Set the rate at which compaction will readd entries. The unit is adds per second.
  # compactionRateByEntries=1000
  # Set the rate at which compaction will readd entries. The unit is bytes added per second.
  # compactionRateByBytes=1000000