apiVersion: "bookkeeper.pravega.io/v1alpha1"
kind: "BookkeeperCluster"
metadata:
  name: {{ template "bookkeeper.fullname" . }}
spec:
  replicas: {{ .Values.replicas }}
  image:
    repository: {{ with .Values.image }}{{ .repository }}{{ end }}
    pullPolicy: {{ with .Values.image }}{{ .pullPolicy }}{{ end }}
  envVars: {{ template "configmap.fullname" . }}
  version: {{ .Values.version }}
  zookeeperUri: {{ .Values.zookeeperUri }}
  autoRecovery: {{ .Values.autoRecovery }}
  storage:
      ledgerVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.storage.className }}
        resources:
          requests:
            storage: 100Gi

      journalVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.storage.className }}
        resources:
          requests:
            storage: 100Gi

      indexVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.storage.className }}
        resources:
          requests:
            storage: 10Gi
  options:
      enableStatistics: "true"
      statsProviderClass: "org.apache.bookkeeper.stats.prometheus.PrometheusMetricsProvider"
      log.level: "INFO"
      ledgerStorageClass: "org.apache.bookkeeper.bookie.InterleavedLedgerStorage"
      flushEntrylogBytes: "134217728"
      minorCompactionThreshold: "0.4"
      minorCompactionInterval: "1800"
      majorCompactionThreshold: "0.8"
      majorCompactionInterval: "43200"
      isForceGCAllowWhenNoSpace: "true"
      gcWaitTime: "600000"
      flushInterval: "60000"
      numAddWorkerThreads: "8"
      entryLogPerLedgerEnabled: "true"
      readBufferSizeBytes: "4096"
      writeBufferSizeBytes: "524288"
      isThrottleByBytes: "true"
      compactionRateByBytes: "1000000"
      journalDirectories: "/bk/journal/j0,/bk/journal/j1,/bk/journal/j2,/bk/journal/j3,/bk/journal/j4,/bk/journal/j5,/bk/journal/j6,/bk/journal/j7"
      ledgerDirectories: "/bk/ledgers/"
  jvmOptions:
    {{- if .Values.jvmOptions }}
{{ toYaml .Values.jvmOptions | indent 4 }}
    {{- end }}
  resources:
    limits:
      cpu: {{ .Values.resources.limits.cpu }}
      memory: {{ .Values.resources.limits.memory }}
    requests:
      cpu: {{ .Values.resources.requests.cpu }}
      memory: {{ .Values.resources.requests.memory }}
